### ISSUE TITLE
Create CHANGELOG.md

### ISSUE THREAD

**Issue by 1toldyou** [technototes/PowerPlay2022#97]
We should have something formal to keep track of changes we make and why we make these changes.

This should be optional, and while we do have descriptive commit messages, if people have time they can compile their reasoning and thinking into a list; imagine there is a reminder of where you left of at the previous workday, help the next person take-over your workload easier by having the context

**Comment by kevinfrei** [comment]
The biggest problem with a change log is that it's *always* a merge conflict. If we want to mandate that it's only edited on Github directly, you could potentially do that. I'd prefer we require descriptive commit messages (or PR messages), simply because that can be automatically turned into a change log.
